;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="UI",DevComment="")
+GameplayTagList=(Tag="UI.Layer",DevComment="")
+GameplayTagList=(Tag="UI.Layer.MainUI",DevComment="Stuff onscreen during main gameplay (icons, hotbar, etc)")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="For menus such as pause and options menus")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="For modals, such as pop up messages")

